[fusiondata]
git-tree-sha1 = "69ab4bb382d7e8dc3829dab83f5d7dcc71fb221c"

    [[fusiondata.download]]
    sha256 = "79062eab4e4c8ab88d34a4311f83d24fc1b9d30fe67656d8dc1f581fd7d2dbc3"
    url = "https://github.com/QuantumKitHub/MultiTensorKit.jl/archive/refs/tags/data-v0.1.4.tar.gz"
