[fusiondata]
git-tree-sha1 = "51945fa48a93f5cce598479303c1a33b1adb1460"

    [[fusiondata.download]]
    sha256 = "9db43abcccb3bef484bf7837eec933cbc9bc5ad7ab3bb2ea13ee70e505f58ca7"
    url = "https://github.com/QuantumKitHub/MultiTensorKit.jl/archive/refs/tags/data-v0.1.2.tar.gz"
