name = "MultiTensorKit"
uuid = "f0555a46-f681-4ef1-bed5-d64870568636"
authors = ["Boris De Vos, Laurens Lootens and Lukas Devos"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"

[compat]
Aqua = "0.8.9"
DelimitedFiles = "1.9"
Pkg = "1"
Random = "1"
SafeTestsets = "0.1"
TensorKit = "0.16"
TensorKitSectors = "0.3"
TensorOperations = "5"
Test = "1.10"
TestExtras = "0.3"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"

[targets]
test = ["Aqua", "Random", "SafeTestsets", "TensorOperations", "Test", "TestExtras"]

[sources]
TensorKitSectors = {url = "https://github.com/QuantumKitHub/TensorKitSectors.jl", rev = "bd/multitestcompat"}